services:
  swagger.request.processor:
    class: KleijnWeb\SwaggerBundle\EventListener\Request\RequestProcessor
    arguments:
      - '@swagger.description.repository'
      - '@swagger.request.validator'
      - '@swagger.request.parameters_assembler'
    public: false

  swagger.request.parameters_assembler:
    class: KleijnWeb\PhpApi\Descriptions\Request\RequestParameterAssembler
    public: false

  swagger.request.validator:
    class: KleijnWeb\PhpApi\Descriptions\Description\Schema\Validator\DefaultValidator
    public: false
