services:
  swagger.response.factory:
    class: KleijnWeb\SwaggerBundle\EventListener\Response\ResponseFactory
    arguments: [~]
    public: false

  swagger.response.error.simple:
    class: KleijnWeb\SwaggerBundle\EventListener\Response\ErrorResponseFactory\SimpleErrorResponseFactory
    public: false

  swagger.response.error.logref_builder:
    class: KleijnWeb\SwaggerBundle\EventListener\Response\Error\LogRefBuilder\UniqueIdLogRefBuilder
    public: false

  swagger.response.error_response_factory.simple:
    class: KleijnWeb\SwaggerBundle\EventListener\Response\ErrorResponseFactory\SimpleErrorResponseFactory
    public: false
